
[general]
	only_affect_block_light = false
	ignore_moon_phase = false
	dark_overworld = true
	dark_default = true
	dark_nether = true
	#Range: 0.0 ~ 1.0
	dark_nether_fog = 0.5
	dark_end = true
	#Range: 0.0 ~ 1.0
	dark_end_fog = 0.0
	dark_skyless = true
	#Range: 0.0 ~ 1.0
	minimum_moon_brightness = 0.0
	#Range: 0.0 ~ 1.0
	maximum_moon_brightness = 1.0
	#Range: 0.0 ~ 1.0
	minimum_light = 0.0

